# Generated by Django 5.1.7 on 2025-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('phone_code', models.CharField(default='+91', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
            ],
        ),
    ]
