# Generated by Django 5.1.7 on 2025-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_rename_address_branch_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='series_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
