# Generated by Django 5.1.7 on 2025-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_series_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='series_prefix',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
