# Generated by Django 5.1.7 on 2025-03-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_series_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
