# Generated by Django 5.1.7 on 2025-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_branch_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='branch',
            name='last_invoice_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='series_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
