# Generated by Django 5.1.7 on 2025-04-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_remove_branch_branch_name_branch_last_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='series_prefix',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
