# Generated by Django 5.1.7 on 2025-03-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='address',
            new_name='branch_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='address',
            new_name='branch_address',
        ),
    ]
