# Generated by Django 5.1.7 on 2025-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_address_branch_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
