# Generated by Django 5.1.7 on 2025-03-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('branch', '0003_branch_series_prefix'),
        ('clients', '0001_initial'),
        ('invoice', '0003_invoice_is_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('invoice_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency_type', models.CharField(max_length=10)),
                ('payment_terms', models.CharField(max_length=50)),
                ('tax_option', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items', models.JSONField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
                ('branch_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
