# Generated by Django 5.1.7 on 2025-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_finalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
