# Generated by Django 5.1.7 on 2025-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_custom_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='custom_invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_final',
        ),
        migrations.DeleteModel(
            name='FinalInvoice',
        ),
    ]
