# Generated by Django 5.1.7 on 2025-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoice_custom_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
