# Generated by Django 5.1.7 on 2025-04-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
