# Generated by Django 5.1.7 on 2025-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_final_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_saved_final',
            field=models.BooleanField(default=False),
        ),
    ]
